version: '2'
services:
  leanote:
    container_name: leanote_app
    image: zuolan/leanote
    ports:
      - "9000:9000"
    volumes:
      - ./app.conf:/leanote/conf/app.conf
      - ./upload:/leanote/public/upload
      - /etc/localtime:/etc/localtime:ro
    links:
      - mongo
    restart: always

  mongo:
    container_name: leanote_db
    image: mongo
    volumes:
      - ./data:/data/db
      - /etc/localtime:/etc/localtime:ro
    restart: always

  initdb:
    container_name: leanote_init
    image: zuolan/mongodb-tools
    links:
      - mongo
    volumes:
      - ./initdb.sh:/initdb.sh
      - ./data:/data/db
    command: sh /initdb.sh

networks:
  default:
    external:
      name: nginx
