version: '2'
services:
  hexo:
    container_name: hexo
    image: zuolan/hexo
    restart: always
    environment:
      - GIT_USER=izuolan
      - GIT_EMAIL=i@zuolan.me
    volumes:
      - ./:/mnt
      - $HOME/.ssh:/root/.ssh
  nginx:
    container_name: blog
    image: nginx:alpine
    restart: always
    volumes:
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "4000:80"
